accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import MyLoginView, MySignupView

app_name = 'accounts'
urlpatterns = [
    path('login/', MyLoginView.as_view(), name='login'),
    path('signup/', MySignupView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout')
]

conf/urls.py
import debug_toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import conf.settings
from job_search.views import custom_handler404, custom_handler500

handler404 = custom_handler404
handler500 = custom_handler500

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('job_search.urls')),
    path('accounts/', include('accounts.urls'))
]

if conf.settings.DEBUG:
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

if conf.settings.DEBUG:
    urlpatterns += static(conf.settings.MEDIA_URL,
                          document_root=conf.settings.MEDIA_ROOT)

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView


class MySignupView(CreateView):

    form_class = UserCreationForm
    success_url = reverse_lazy('accounts:login')
    template_name = 'accounts/register.html'


class MyLoginView(LoginView):
    redirect_authenticated_user = True
    template_name = 'accounts/login.html'

accounts/templates/accounts/auth_base.html
<!DOCTYPE html>
<html lang="ru">

<head>
  <title>Джуманджи</title>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
  <main class="container">
    <div class="row">
      <div class="col-8 col-lg-4 offset-2 offset-lg-4">
          <a href="{% url "index" %}"><h1 class="h3 mb-3 font-weight-normal">Джуманджи</h1></a>
            <p class="h5 font-weight-light">Войдите, чтобы управлять</p>
          {% block content %}
            {% endblock %}
      </div>
    </div>
  </main>
</body>
</html>

accounts/templates/accounts/login.html
{% extends 'accounts/auth_base.html' %}
{% block content %}
        <form method="post" action="{% url 'accounts:login' %}">{% csrf_token %}
            <table>{{ form.as_table }}</table>
            <button type="submit">login</button>
        </form>
        <div class="mt-4 text-center"><p>Нет аккаунта? <a href="{% url 'accounts:signup' %}">Зарегистрируйтесь!</a></p></div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'accounts/auth_base.html' %}
{% block content %}
          <form method="post" action="{% url 'accounts:signup' %}">{% csrf_token %}
            <table>{{ form.as_table }}</table>
            <button type="submit">Send</button>
        </form>


         <div class="mt-4 text-center"><p>Есть аккаунт? <a href="{% url 'accounts:login' %}">Войдите!</a></p></div>
{% endblock %}