accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import MyLoginView, MySignupView

app_name = 'accounts'
urlpatterns = [
    path('login/', MyLoginView.as_view(), name='login'),
    path('signup/', MySignupView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout')
]

conf/urls.py
import debug_toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import conf.settings
from job_search.views import custom_handler404, custom_handler500

handler404 = custom_handler404
handler500 = custom_handler500

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('job_search.urls')),
    path('accounts/', include('accounts.urls'))
]

if conf.settings.DEBUG:
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

if conf.settings.DEBUG:
    urlpatterns += static(conf.settings.MEDIA_URL,
                          document_root=conf.settings.MEDIA_ROOT)

job_search/urls.py
from django.urls import path

from .views import VacancyView, MainView, VacanciesView, CompanyView, VacanciesByCategoryView, CompanyCreateView, \
    CompanyLetsstart, CompanyEditView, MyCompanyVacancies, MyCompanyNewVacancy, MyCompanyEditVacancy, application_send

urlpatterns = [
    path('vacancies/cat/<str:category>/', VacanciesByCategoryView.as_view(), name='vacancies_by_cat'),
    path('vacancies/<int:vacancy_pk>/', VacancyView.as_view(), name='vacancy'),
    path('', MainView.as_view(), name='index'),
    path('companies/<int:company_pk>/', CompanyView.as_view(), name='company'),
    path('vacancies/', VacanciesView.as_view(), name='vacancies'),
    path('mycompany/', CompanyEditView.as_view(), name='my_company'),
    path('mycompany/letsstart/', CompanyLetsstart.as_view(), name='new_company'),
    path('mycompany/create', CompanyCreateView.as_view(), name='create_company'),
    path('mycompany/vacancies', MyCompanyVacancies.as_view(), name='my_vacancies'),
    path('mycompany/new_vacancy', MyCompanyNewVacancy.as_view(), name='new_vacancy'),
    path('mycompany/vacancy/<int:vacancy_pk>', MyCompanyEditVacancy.as_view(), name='my_vacancy_edit'),
    path('vacancy/application_send', application_send, name='application_send')
]

job_search/models.py
from django import conf
from django.contrib.auth.models import User
from django.db import models
# Create your models here.
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class Company(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название компании")
    location = models.CharField(max_length=100, verbose_name="Местоположение")
    logo = models.ImageField(upload_to=conf.settings.MEDIA_COMPANY_IMAGE_DIR, default='logo')
    description = models.TextField(verbose_name="Описание")
    employee_count = models.IntegerField(verbose_name="Количество сотрудников")
    owner = models.OneToOneField(User, on_delete=models.CASCADE, null=True, related_name='mycompany')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('index')


class Speciality(models.Model):
    code = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    picture = models.ImageField(upload_to=conf.settings.MEDIA_SPECIALITY_IMAGE_DIR)

    def __str__(self):
        return self.title


class Vacancy(models.Model):
    title = models.CharField(max_length=100,  verbose_name='Название вакансии')
    skills = models.TextField(verbose_name='Навыки')
    description = models.TextField(verbose_name='Описание')
    salary_min = models.IntegerField(verbose_name='Минимальная ЗП')
    salary_max = models.IntegerField(verbose_name='Максимальная ЗП')
    published_at = models.DateTimeField()
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="vacancies")
    specialty = models.ForeignKey(Speciality,
                                  on_delete=models.CASCADE,
                                  related_name="vacancies",
                                  verbose_name="Специализация"
                                  )

    def __str__(self):
        return self.title


class Application(models.Model):
    written_username = models.CharField(max_length=100, verbose_name="Ваше имя")
    written_phone = models.CharField(max_length=20, verbose_name="Ваш телефон")
    written_cover_letter = models.TextField(verbose_name="Сопроводительное письмо")
    vacancy = models.ForeignKey(Vacancy, on_delete=models.CASCADE, related_name='applications')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='applications')

    def __str__(self):
        return f"Application from {self.user}"


class Resume(models.Model):

    class Grade(models.TextChoices):
        FRESHMAN = 'FR', _('Стажер')
        JUNIOR = 'JR', _('Джуниор')
        MIDDLE = 'MD', _('Миддл')
        SENIOR = 'SR', _('Синьор')
        LEAD = 'LD', _('Лид')

    class Status(models.TextChoices):
        SEARCHING = 'SR', _("Ищу работу")
        NOT_SEARCHING = 'NS', _("Не ищу работу")
        SEMI = 'SM', _('Рассматриваю предложения')

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name='Имя')
    surname = models.CharField(max_length=100, verbose_name='Фамилия')
    grade = models.CharField(max_length=2, choices=Grade.choices, default=Grade.FRESHMAN)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.SEARCHING)
    salary = models.IntegerField(verbose_name='Вознаграждение')
    specialty = models.ForeignKey(Speciality, verbose_name='Специализация', on_delete=models.CASCADE)
    education = models.TextField(verbose_name="Образование")
    experience = models.TextField(verbose_name="Образование")
    portfolio = models.TextField(verbose_name="Портфолио")

job_search/forms.py
from django import forms

from job_search.models import Company, Vacancy, Application


class CompanyCreateForm(forms.ModelForm):

    class Meta:
        model = Company
        field = [
            'name',
            'location',
            'logo',
            'description',
            'employee_count'
        ]
        exclude = ('owner',)


class VacancieCreateForm(forms.ModelForm):

    class Meta:
        model = Vacancy
        field = [
            'title',
            'skills',
            'description',
            'salary_min',
            'salary_max',
            'specialty'
        ]
        exclude = ('company', 'published_at')

    def clean(self):
        super(VacancieCreateForm, self).clean()
        salary_min = self.cleaned_data.get('salary_min')
        salary_max = self.cleaned_data.get('salary_max')
        if salary_min > salary_max:
            self.add_error('salary_min', 'Min > Max')


class ApplicationCreateForm(forms.ModelForm):

    class Meta:
        model = Application
        field = [
            'written_username',
            'written_phone',
            'written_cover_letter'
        ]
        exclude = ('vacancy', 'user')

job_search/views.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.http import Http404, HttpResponseNotFound, HttpResponseServerError, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import TemplateView, ListView

from .forms import CompanyCreateForm, VacancieCreateForm, ApplicationCreateForm
from .models import Vacancy, Company, Speciality, Application


class VacancyView(TemplateView):
    template_name = 'job_search/vacancy.html'

    def get_context_data(self, **kwargs):
        context = super(VacancyView, self).get_context_data(**kwargs)
        context['vacancy'] = get_object_or_404(Vacancy, pk=context['vacancy_pk'])  # объект по ключу из url
        application_form = ApplicationCreateForm()
        context['form'] = application_form
        return context

    def post(self, request, vacancy_pk):
        application_form = ApplicationCreateForm(request.POST)
        if application_form.is_valid():
            new_application = application_form.save(commit=False)
            new_application.vacancy = get_object_or_404(Vacancy, id=vacancy_pk)
            new_application.user = request.user
            new_application.save()
            return HttpResponseRedirect(reverse('application_send'))


def application_send(request):
    return render(request, template_name='job_search/application_send.html')


class MainView(TemplateView):
    template_name = 'job_search/index.html'

    def get_context_data(self, **kwargs):
        context = super(MainView, self).get_context_data(**kwargs)
        context['companies'] = Company.objects.annotate(num_vacancies=Count('vacancies'))
        context['specialities'] = Speciality.objects.annotate(num_vacancies=Count('vacancies'))
        return context


class VacanciesView(ListView):
    template_name = 'job_search/vacancies.html'
    model = Vacancy
    context_object_name = 'vacancies'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(VacanciesView, self).get_context_data(**kwargs)
        context['title'] = "Все вакансии"  # Тайтл в темплэйт
        return context


class VacanciesByCategoryView(ListView):
    # вакансии по специализации
    template_name = 'job_search/vacancies.html'
    model = Vacancy
    context_object_name = 'vacancies'

    def get_context_data(self, *, object_list=None, **kwargs):

        context = super(VacanciesByCategoryView, self).get_context_data(**kwargs)
        category = get_object_or_404(Speciality, code=self.kwargs['category'])
        context['title'] = category.title  # Тайтл в темплэйте.
        return context

    def get_queryset(self):
        try:
            category = self.kwargs['category']
            speciality = get_object_or_404(Speciality, code=category)  # наличие специализации из урла в списке
            return Vacancy.objects.filter(specialty=speciality)   # поиск по специализации
        except KeyError:
            raise Http404


class CompanyView(TemplateView):
    template_name = 'job_search/company.html'

    def get_context_data(self, **kwargs):
        context = super(TemplateView, self).get_context_data(**kwargs)
        context['company'] = get_object_or_404(Company, pk=context['company_pk'])  # объект по ключу из url
        return context


class CompanyLetsstart(LoginRequiredMixin, TemplateView):
    template_name = 'job_search/company_create.html'


class CompanyCreateView(LoginRequiredMixin, View):

    def get(self, request):
        company_form = CompanyCreateForm()
        context = {
            'form': company_form,
        }
        return render(request, template_name='job_search/company_edit.html', context=context)

    def post(self, request):

        company_form = CompanyCreateForm(request.POST, request.FILES)

        if company_form.is_valid():
            new_company = company_form.save(commit=False)
            new_company.owner = request.user
            new_company.save()

        return HttpResponseRedirect(reverse('my_company'))


class CompanyEditView(LoginRequiredMixin, View):
    # Вью для просмотра и редактирования информации о компании
    # При переходе на 'my_company' проверяет привязана ли компания к пользователю.
    # Если компании нет, то кидает на 'new_company'
    # Если есть, то на страницу редактирования компании
    # я не сообразил как заставить по дефолту указывать существующий url картинки,
    # поэтому проверка на дефолтный урл logo_default_url
    logo_default_url = 'logo'

    def get(self, request):
        try:
            company = Company.objects.get(owner=request.user)
        except Company.DoesNotExist:
            return HttpResponseRedirect(reverse('new_company'))
        company_form = CompanyCreateForm(instance=company)
        context = {
            'form': company_form,
            'company': company  # для отображения логотипа
        }
        return render(request, template_name='job_search/company_edit.html', context=context)

    def post(self, request):
        actual_company = get_object_or_404(Company, owner=request.user)
        company_form = CompanyCreateForm(request.POST, request.FILES)
        edited = False
        if company_form.is_valid():
            for field_name, field_value in company_form.cleaned_data.items():
                # logo обрабатывается по другому, так как не поборол проблему с дефолтным...
                # При обновлении формы через render logo скидывается на дефолтное
                # соответственно, если дефолтное или поменялось, то меняем на новое
                if field_value != getattr(actual_company, field_name) and field_name != 'logo':
                    setattr(actual_company, field_name, field_value)
                    edited = True
                if field_name == 'logo' and field_value not in \
                        [
                            self.logo_default_url,
                            getattr(actual_company, field_name)
                        ]:
                    actual_company.logo.storage.delete(actual_company.logo.path)
                    setattr(actual_company, field_name, field_value)
                    edited = True

            if edited:
                actual_company.save()

            company_form = CompanyCreateForm(instance=actual_company)
            context = {
                'form': company_form,
                'company': actual_company,  # для отображения картинки
                'edited': edited
            }
            return render(request, template_name='job_search/company_edit.html', context=context)


class MyCompanyVacancies(LoginRequiredMixin, View):
    template_name = 'job_search/myvacancies.html'

    def get(self, request):
        try:
            company = Company.objects.get(owner=self.request.user)
        except Company.DoesNotExist:
            return HttpResponseRedirect(reverse('new_company'))

        vacancies = Vacancy.objects.filter(company=company).annotate(num_applications=Count('applications'))

        context = {
            'vacancies': vacancies
        }
        return render(request, template_name=self.template_name, context=context)


class MyCompanyNewVacancy(LoginRequiredMixin, View):
    template = 'job_search/vacancy_edit.html'
    # класс для создания новой вакансии

    def get(self, request):
        vacancy_form = VacancieCreateForm()
        context = {
            'vacancy_form': vacancy_form
        }
        return render(request, template_name=self.template, context=context)

    def post(self, request):
        vacancy_form = VacancieCreateForm(request.POST)

        if vacancy_form.is_valid():
            new_vacancy = vacancy_form.save(commit=False)
            try:
                company = Company.objects.get(owner=request.user)
            except Company.DoesNotExist:
                return HttpResponseRedirect(reverse('new_company'))
            new_vacancy.company = company
            new_vacancy.published_at = datetime.today()
            new_vacancy.save()

        return HttpResponseRedirect(reverse('my_vacancies'))


class MyCompanyEditVacancy(LoginRequiredMixin, View):
    template = 'job_search/vacancy_edit.html'

    def get(self, request, vacancy_pk):
        try:
            company = Company.objects.get(owner=request.user)
        except Company.DoesNotExist:
            return redirect('new_company')

        try:
            vacancy = Vacancy.objects.get(id=vacancy_pk, company=company)
        except Vacancy.DoesNotExist:
            return redirect('my_vacancies')

        vacancy_form = VacancieCreateForm(instance=vacancy)
        applications = Application.objects.filter(vacancy=vacancy)
        context = {
            'vacancy_form': vacancy_form,
            'applications': applications
        }
        return render(request, template_name=self.template, context=context)

    def post(self, request, vacancy_pk):
        vacancy_form = VacancieCreateForm(request.POST)
        try:
            company = Company.objects.get(owner=request.user)
        except Company.DoesNotExist:
            return redirect('new_company')

        try:
            actual_vacancy = Vacancy.objects.get(id=vacancy_pk, company=company)
        except Vacancy.DoesNotExist:
            return redirect('my_vacancies')
        edited = False
        if vacancy_form.is_valid():
            # Проверка на то, что нужно поменять в актуальной вакансии
            # Если ничего не поменялось, то просто редирект, если менялось, то добавляется edited = True
            for field_name, field_value in vacancy_form.cleaned_data.items():
                if field_value != getattr(actual_vacancy, field_name):
                    setattr(actual_vacancy, field_name, field_value)
                    edited = True
            if edited:

job_search/templates/job_search/application_send.html
{% extends 'job_search/base.html' %}
{% load static %}
{% block content %}
      <main class="container mt-3 pb-5">
    <div class="row mt-5">
      <div class="col-10 col-md-6 offset-1 offset-md-3 mt-5">
        <div class="card mb-3">
          <div class="card-body text-center pt-5">
            <img src="{% static 'check.png' %}" width="65" alt="">
            <h2 class="h5 card-title mt-4 mb-2">Отклик отправлен</h2>
            <p><a href="{{ request.META.HTTP_REFERER }}">Вернуться к вакансии</a></p>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

job_search/templates/job_search/base.html
<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <title>Вакансия | Джуманджи</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
  <header class="container mt-3">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand mr-4 font-weight-bold" href="{% url 'index' %}">Джуманджи</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
        <ul class="navbar-nav col-10">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'vacancies' %}">Вакансии</a>
          </li>

        </ul>
        <ul class="navbar-nav col-2 justify-content-end">
          <li class="nav-item active">
          {{ request.user.auth }}
            {% if user.is_authenticated  %}
                <div class="btn-group">
              <button type="button" class="btn dropdown-toggle font-weight-bold" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ user.username }}
              </button>
              <div class="dropdown-menu dropdown-menu-right mt-3">
                <a href="#" class="dropdown-item py-2">Профиль</a>
                <a href="#" class="dropdown-item py-2">Резюме</a>
                <a href="{% url 'my_company' %}" class="dropdown-item py-2">Компания</a>
                <a href="{% url 'accounts:logout' %}" class="dropdown-item py-2">Выйти</a>
              </div>
            </div>
            {% else %}
              <a href="{% url 'accounts:login' %}" class="nav-link font-weight-bold">Вход</a>
            {% endif %}
          </li>
        </ul>
      </div>
    </nav>
  </header>
  {% block content %}
  {% endblock %}
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

job_search/templates/job_search/company.html
{% extends 'job_search/base.html' %}
{% load ru_pluralize %}
{% load switch_symb %}
{% load thous_sep %}
{% block content %}
  <main class="container mt-3">
    <div class="col-12 col-lg-2">
      <p><a href="{{ request.META.HTTP_REFERER }}">Назад</a></p>
    </div>
    <section>
      <div class="text-center">
        <img src="{{ company.logo.url }}" width="auto" height="300" alt="">
      </div>
      <h1 class="h1 text-center mx-auto mt-0 pt-1" style="font-size: 70px;"><strong>{{ company.name|capfirst }}</strong></h1>
      <p class="text-center pt-1">Компания, {{ company.location }}, {{ company.vacancies.count|ru_pluralize:"вакансия,вакансии,вакансий" }}</p>
      <div class="row mt-5">
        <div class="col-12 col-lg-8 offset-lg-2 m-auto">
            {% for vacancy in company.vacancies.all %}
          <div class="card mb-4">

            <div class="card-body px-4">
              <div class="row">
                <div class="col-12 col-md-8 col-lg-9">
                 <a href="{% url 'vacancy' vacancy.pk %}" class="stretched-link"> <h2 class="h2 pb-2">{{ vacancy.title }}</h2></a>
                  <p class="mb-2">{{ vacancy.skills|switch_symb:",& •" }}</p>
                  <p>От {{ vacancy.salary_min|thous_sep }} до {{ vacancy.salary_max|thous_sep }} руб.</p>
                  <p class="text-muted pt-1">
                      {{vacancy.published_at|date:"d E"}}</p>
                </div>
                <div class="col-12 col-md-4 col-lg-3 d-flex align-items-end">
                  <img src="{{ vacancy.specialty.picture.url }}" width="150" height="auto" alt="">
                </div>
              </div>
            </div>

          </div>
            {% endfor %}
        </div>
      </div>
    </section>
  </main>
{% endblock %}

job_search/templates/job_search/company_create.html
{% extends 'job_search/base.html' %}
{% block content %}
  <main class="container mt-3 pb-5">
    <section class="col-12 col-lg-6 offset-lg-3 mt-5 card">
      <div class="card-body px-3 pb-4">
        <h1 class="h4 pt-2">Моя компания</h1>
        <p class="mt-2">Пока мы думаем, что вы – частное лицо. Хотите создать карточку компании, разместить информаию и вакансии?</p>
        <a href="{% url 'create_company' %}" class="btn btn-info mb-2">Создать карточку компании</a>
      </div>
    </section>
  </main>
{% endblock %}

job_search/templates/job_search/company_edit.html
{% extends 'job_search/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <main class="container mt-3 pb-5">
    <div class="row mt-5">
      <div class="col-12 col-lg-4">
        <aside class="pt-3 pb-4 px-4 mb-5 card">
          <h1 class="h4 pt-2 pb-2">Моя компания</h1>
          <div class="nav flex-column nav-pills">
            <a class="nav-link active" href="#">1. Информация о компании</a>
            <a class="nav-link" href="{% url 'my_vacancies' %}">2. Вакансии</a>
          </div>
        </aside>
      </div>
      <div class="col-12 col-lg-8">
        <div class="card">
          <div class="card-body px-4 pb-4">
            <!-- Tab -->
            <section class="tab-pane fade show active">
              <h2 class="h4 pt-2 pb-3">Информация о&nbsp;компании</h2>
                {% if edited %}
              <p class="alert alert-info" role="alert">
                Информация о компании обновлена
              </p>
                {% endif %}
              <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                <div class="row">
                  <div class="col-12 col-md-6">
                    <div class="form-group pb-2">
                        {{ form.name|as_crispy_field }}
                    </div>
                  </div>
                  <div class="col-12 col-md-6">
                    <div class="form-group">
                      <label class="mb-2 text-dark" for="companyLogo">Логотип</label>
                      <div class="row align-items-center">
                        <div class="col-6">
                          <img src="{{ company.logo.url }}" alt="123" style="max-width: 120px;height: auto;">
                        </div>
                        <div class="col-4" style="position: relative;">

                            {{ form.logo|as_crispy_field }}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-12 col-md-6">
                    <div class="form-group pb-2">
                        {{ form.employee_count|as_crispy_field }}
                    </div>
                  </div>
                  <div class="col-12 col-md-6">
                    <div class="form-group pb-2">
                        {{ form.location|as_crispy_field }}
                    </div>
                  </div>
                </div>
                <div class="form-group pb-2">
                  {{ form.description|as_crispy_field }}
                </div>
                <div class="form-group">
                  <input type="submit" class="btn btn-info" value="Сохранить">
                </div>
              </form>




                     </section>
            <!-- END Tab -->
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

job_search/templates/job_search/company_new.html
{% extends 'job_search/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <main class="container mt-3 pb-5">
    <div class="row mt-5">
      <div class="col-12 col-lg-4">
        <aside class="pt-3 pb-4 px-4 mb-5 card">
          <h1 class="h4 pt-2 pb-2">Моя компания</h1>
          <div class="nav flex-column nav-pills">
            <a class="nav-link active" href="#">1. Информация о&nbsp;компании</a>
            <a class="nav-link" href="#">2. Вакансии</a>
          </div>
        </aside>
      </div>
      <div class="col-12 col-lg-8">
        <div class="card">
          <div class="card-body px-4 pb-4">
            <!-- Tab -->
            <section class="tab-pane fade show active">
              <h2 class="h4 pt-2 pb-3">Информация о&nbsp;компании</h2>

              <form method="post" action="{% url "create_company" %}" enctype="multipart/form-data">
                  {% csrf_token %}
                  <table>
                    {%  crispy form "bootstrap4" %}
                </table>
                  <button type="submit">Submit</button>
              </form>




                     </section>
            <!-- END Tab -->
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

job_search/templates/job_search/myvacancies.html
{% extends 'job_search/base.html' %}
{% load ru_pluralize %}
{% load thous_sep %}
{% block content %}
  <main class="container mt-3 pb-5">
    <div class="row mt-5">
      <div class="col-12 col-lg-4">
        <aside class="pt-3 pb-4 px-4 mb-5 card">
          <h1 class="h4 pt-2 pb-2">Моя компания</h1>
          <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <a class="nav-link" href="{% url 'my_company' %}">1. Информация о компании</a>
            <a class="nav-link active" href="#">2. Вакансии</a>
          </div>
        </aside>
      </div>
      <div class="col-12 col-lg-8">
          <a href="{% url 'new_vacancy' %}" class="btn btn-primary btn-lg btn-block my-4">Создать вакансию<a>

        <div class="card">
          <div class="card-body px-4 pb-4">
            <section class="tab-pane fade show active">
              <h2 class="h4 pt-2 pb-3">Вакансии</h2>
              <!-- vacancy state 1 -->
                {% for vacancy in vacancies %}
                  <div class="card mt-3">
                <div class="card-body px-4">
                  <div class="row align-items-center">
                    <div class="col-6 col-lg-8">
                      <a href="{% url 'my_vacancy_edit' vacancy.pk %}" class="mb-1">{{ vacancy.title }}</a>
                      <p class="mb-1">
                        <span class="mr-4">{{ vacancy.salary_min|thous_sep }} - {{ vacancy.salary_max|thous_sep }}</span><a href="{% url 'my_vacancy_edit' vacancy.pk %}#appl" class="text-info">{{ vacancy.num_applications|ru_pluralize:"отклик,отклика,откликов" }}</a>
                      </p>
                    </div>
                    <div class="col-6 col-lg-4 text-right">
                      <a href="{% url 'my_vacancy_edit' vacancy.pk %}" class="btn btn-outline-info">Изменить</a>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}

            </section>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}